export const CHURCHES = [
  {
    "city": "Darmstadt",
    "name": "Calvary Chapel Darmstadt",
    "pastor": "Frank Decker",
    "website": "www.calvarydarmstadt.de",
    "address": "Roßdörfer Str. 35a, 64409 Messel bei Darmstadt",
    "services": "See website",
    "godis": "siehe Webseite",
    "email": null
  },
  {
    "city": "Düsseldorf",
    "name": "Calvary Chapel Düsseldorf",
    "pastor": "Edmund Coronel Jr.",
    "website": "www.calvarychapelduesseldorf.de",
    "address": "Düsselthaler Str. 9, 40211 Düsseldorf",
    "services": "Sunday 10:30 AM",
    "godis": "Sonntag 10.30 Uhr",
    "email": null
  },
  {
    "city": "Freiburg",
     "name": "Calvary Chapel Freiburg",
    "pastor": "Alex Röhm",
    "website": "www.ccfreiburg.de",
    "address": "Löwenstr. 3-7, 79098 Freiburg",
    "services": "Sunday 9:30 AM (German), 11:30 AM (German), 5:00 PM (English); Wednesday 7:00 PM (German)",
    "godis": "Sonntag 9:30 Uhr (deutsch) / 11.30 Uhr (deutsch) / 17 Uhr (englisch) / Mittwoch 19.00 Uhr (deutsch)",
    "podcast": "https://podcast.ccfreiburg.de/",
    "email": "info@ccfreiburg.de"
  },
  {
    "city": "Neunkirchen",
    "name": "Calvary Chapel Freier Grund",
    "pastor": "Andrew Rann",
    "website": "www.ccfg.de",
    "address": "Bitzegarten 5, 57290 Neunkirchen",
    "services": "Sunday 10:30 AM; Wednesday 7:30 PM",
    "godis": " Sonntag 10:30 Uhr / Mittwoch 19:30 Uhr",
    "stream": "http://www.ccfg.de/index.php/topmenuepredigten/livestream",
    "phone": "+4927356565615",
    "email": "info@ccfg.de"
  },
  {
    "city": "Görlitz",
    "name": "Calvary Chapel Görlitz",
    "pastor": "Stephan Spielau",
    "website": "calvarychapelgoerlitz.de",
    "address": "Parkstr. 3, 02826 Görlitz",
    "services": "Sunday 12:30 PM; Wednesday 7:30 PM",
    "godis": "Sonntags: 12.30 Gottesdienst, 19.30 Gebetsabend, Mittwochs: 19.30 Bibelstunde",
    "email": null
  },
  {
    "city": "Grünstadt",
    "name": "Calvary Chapel Grünstadt",
    "pastor": "Günter Weber",
    "website": "ccgruenstadt.de",
    "address": "Dieselstr. 13, 67269 Grünstadt",
    "services": "Sunday 10:30 AM; Tuesday 7:30 PM",
    "godis": "Sonntag 10.30 Uhr / Dienstag 19.30 Uhr",
    "phone": "+496359961506",
    "email": "ccgruenstadt@gmx.de"
  },
  {
    "city": "Hamburg",
     "name": "City Light Hamburg",
   "pastor": "Janos Hench",
    "website": "citylighthamburg.de",
    "address": "Mexikoring 15, 22297 Hamburg",
    "services": "Sunday 4:00 PM",
    "godis": "Sonntag 16 Uhr",
    "phone": "+49 40 3346675 88",
    "email": "info@citylighthamburg.de"
  },
  {
    "city": "Hannover",
    "name": "Koinonia Calvary Chapel Hannover",
    "pastor": "Jörg Macheil",
    "website": "koinonia-gemeinde.de",
    "address": "Herrenstr. 10, 30159 Hannover",
    "services": "Sunday 10:30 AM; Wednesday 7:30 PM",
    "godis": "Sonntag 10:30 Uhr und Mittwoch 19:30 Uhr (Eingang Herrenstr. 8a)",
    "stream": "http://koinonia-radio.de/",
    "podcast": "https://koinonia-gemeinde.de/mp3/podcast48.xml",
    "email": null
  },
  {
    "city": "Heidelberg",
     "name": "Calvary Chapel Heidelberg",
   "pastor": "Keith Fortenberry",
    "website": "www.cchd.de",
    "address": "Vangerowstr. 51a, 69115 Heidelberg",
    "services": "Sunday 10:30 AM; 7:00 PM",
    "godis": "Sonntag 10:30 / 19:00 Uhr",
    "stream": "",
    "podcast": "http://www.cchd.de/Predigten_podcast.xml",
    "phone": "+49 6221 433",
    "email": "office@cchd.de"
  },
  {
    "city": "Herborn",
     "name": "Calvary Chapel Herborn",
     "pastor": "Benjamin Rothe",
   "website": "ccherborn.de",
    "address": "Hohe Str. 700, Gebäude 9, 35745 Herborn",
    "services": "Sunday 10:30 AM; Wednesday 7:30 PM",
    "godis": "Sonntag 10:30 / Mittwoch 19:30 Uhr",
    "stream": "",
    "podcast": "https://itunes.apple.com/de/podcast/calvary-chapel-herborn-podcast/id1364863713?l=en",
    "phone": "+49 2772 9230699",
    "email": "office@ccherborn.de"
  },
  {
    "city": "Kindsbach",
     "name": "Calvary Chapel Kaiserslautern",
    "pastor": "David Ball",
    "website": "cck-town.org",
    "address": "Industriestr. 50, 66862 Kindsbach",
    "services": "Sunday 11:00 AM",
    "godis": "Sonntag 11 Uhr",
    "stream": "",
    "podcast": "http://cck-town.org/feed/podcast",
    "phone": "+49 6371 616793",
    "email": null
  },
  {
    "city": "Leipzig",
     "name": "Calvary Chapel Leipzig",
    "pastor": "Kurt Ibbotson",
    "website": "www.calvarychapelleipzig.de",
    "address": "Talstr. 30, 04103 Leipzig",
    "services": "See website",
    "godis": "siehe Webseite",
    "stream": "",
    "podcast": "",
    "phone": "+49 179 7637558",
    "email": "diekapelleleipzig@gmail.com"
  },
  {
    "city": "Lippstadt",
     "name": "Calvary Chapel Lippstadt",
    "pastor": "Rolf Credé",
    "website": "www.cc-lp.de",
    "address": "Windmüllerstraße 22, 59557 Lippstadt",
    "services": "Sunday 10:30 AM; Wednesday 7:30 PM",
    "godis": "Sonntag 10:30 Uhr / Mittwoch 19.30 Uhr",
    "stream": "",
    "podcast": "",
    "email": null
  },
  {
    "city": "Ludwigsburg",
     "name": "City Chapel Ludwigsburg",
    "pastor": "",
    "website": "citychapel-lb.de",
    "address": "Friedenstraße 35, 71636 Ludwigsburg",
    "services": "Sunday 4:00 PM",
    "godis": "Sonntag 16:00 Uhr",
    "stream": "",
    "podcast": "",
    "email": null
  },
  {
    "city": "Minden",
     "name": "Calvary Chapel Minden",
    "pastor": "Ruben-Samuel Will",
    "website": "ccminden.de",
    "address": "Karlsbader Weg 5, 32427 Minden",
    "services": "See website",
    "godis": "siehe Webseite",
    "stream": "",
    "podcast": "",
    "email": null
  },
  {
    "city": "Münster",
     "name": "Livestone Chapel Münster",
    "pastor": "Achim Paul",
    "website": "www.livestonechapel.de",
    "address": "Robert Bosch Str. 5, 48153 Münster",
    "services": "See website",
    "godis": "siehe Webseite",
    "stream": "",
    "podcast": "",
    "phone": "+49 251 87 15 60 35",
    "email": "info@livestonechapel.de"
  },
  {
    "city": "Rostock",
     "name": "LightHouse Rostock",
    "pastor": "Arne Schultze-Petzold",
    "website": "light-house-rostock.de",
    "address": "Kurt-Schumacher-Ring 123, 18069 Rostock",
    "services": "Sunday 11:00 AM",
    "godis": "Sonntag um 11 Uhr",
    "stream": "",
    "podcast": "",
    "email": null
  },
  {
    "city": "Siegen",
     "name": "Calvary Chapel Siegen",
    "pastor": "Alexander Kruse",
    "website": "www.cc-siegen.de",
    "address": "Alte Eisenstr. 6, 57080 Siegen",
    "services": "Sunday 9:30 AM, 11:30 AM, 5:00 PM; Wednesday 7:30 PM",
    "godis": "Sonntag 9:30 / 11:30 / 17:00 Uhr",
    "stream": "https://www.cc-siegen.de/livestream/",
    "podcast": "http://podcasts.subsplash.com/1d0fcbd/podcast.rss",
    "phone": "+49 271 313 8888-8",
    "email": "office@cc-siegen.de"
  },
  {
    "city": "Sinsheim",
     "name": "Vaterhaus Calvary Chapel Sinsheim",
    "website": "calvarychapelsinsheim.de",
    "address": "Am Leitzelbach 20, 74889 Sinsheim",
    "services": "See website",
    "godis": "siehe Webseite",
    "stream": "",
    "podcast": "",
    "email": null
  },
  {
    "city": "Stuttgart",
     "name": "City Chapel Stuttgart",
    "pastor": "Roland Krumm",
    "website": "calvarychapelstuttgart.de",
    "address": "Talstraße 70, 70188 Stuttgart",
    "services": "Sunday 10:00 AM; 6:00 PM",
    "godis": "Sonntag 10:00 Uhr / 18:00 Uhr (verschiedene Adressen, siehe Webseite)",
    "stream": "",
    "podcast": "https://www.citychapel.de/feed/?post_type=sermons",
    "phone": "+49 711-614-29",
    "email": "info@citychapel.de"
  },
  {
    "city": "Wiesbaden",
     "name": "Calvary Chapel Wiesbaden",
    "pastor": "Ron Hostetler",
    "website": "www.calvarychapelwiesbaden.de",
    "address": "Dotzheimer Str. 51, 65197 Wiesbaden",
    "services": "Sunday 10:30 AM; Tuesday 7:30 PM",
    "godis": "Sonntag 10.30 Uhr / Dienstag 19.30 Uhr",
    "stream": "",
    "podcast": "http://www.calvarychapelwiesbaden.de/index.php?option=com_sermonspeaker&view=feed&format=raw&sermon_cat=127&type=audio&Itemid=437",
    "phone": "+49 611 510",
    "email": "info@calvarychapelwiesbaden.de"
  }
]
